// ============================================================
// Amalgamated file for target: gtdependencyquery
// Auto-generated by docker/amalgamate.py
// DO NOT EDIT – changes will be overwritten.
// ============================================================



// ===== Begin: apps/clients/utilities/gt_query.cpp =====
#if 0


using namespace Gadgetron;

static void usage()
{
    using namespace std;
    std::ostringstream outs;

    outs << "Query the gadgetron server for the stored dependency measurements" << endl;
    outs << "gtdependencyquery   -p <PORT>                      (default 9002)" << endl;
    outs << "                    -h <HOST>                      (default localhost)" << endl;
    outs << "                    -o <Query out file>            (default dependency.xml)" << endl;
    outs << std::ends; 

    GDEBUG_STREAM(outs.str());
}

int ACE_TXAIN(int argc, ACE_TCHAR *argv[] )
{
    GadgetronConnector con;

    std::string host("localhost");
    std::string port("9002");
    std::string out("dependency.xml");

    static const ACE_TCHAR options[] = ACE_TEXT(":p:h:o:");

    ACE_Get_Opt cmd_opts(argc, argv, options);

    int option;
    while ((option = cmd_opts()) != EOF)
    {
        switch (option) {
        case 'p':
            port = std::string(cmd_opts.opt_arg());
            break;
        case 'h':
            host = std::string(cmd_opts.opt_arg());
            break;
        case 'o':
            out = std::string(cmd_opts.opt_arg());
            break;
        case ':':
            usage();
            GERROR("-%c requires an argument.\n", cmd_opts.opt_opt());
	    return -1;
            break;
        default:
            usage();
            GERROR("Command line parse error\n");
	    return -1;
            break;
        }
    }

    if (con.open(host,port) != 0)
    {
      GERROR("Unable to connect to the Gadgetron host\n");
      return -1;
    }

    // need to register a reader
    con.register_reader(GADGET_MESSAGE_DEPENDENCY_QUERY, new DependencyQueryReader(out));

    //Tell Gadgetron which XML configuration to run.
    if (con.send_gadgetron_configuration_file(std::string("gtquery.xml")) != 0)
    {
      GERROR("Unable to send XML configuration to the Gadgetron host\n");
      return -1;
    }

    GadgetContainerMessage<GadgetMessageIdentifier>* m1 =
            new GadgetContainerMessage<GadgetMessageIdentifier>();

    m1->getObjectPtr()->id = GADGET_MESSAGE_CLOSE;

    if (con.putq(m1) == -1)
    {
      GERROR("Unable to put CLOSE package on queue\n");
      return -1;
    }

    con.wait();

    return 0;
}

#endif// ===== End: apps/clients/utilities/gt_query.cpp =====


// ===== Begin: apps/clients/utilities/DependencyQueryReader.h =====

/** \file   DependencyQueryReader.h
    \brief  Implement the writer to write the dependency query reults into a file
    \author Hui Xue
*/


#if 0

#include <fstream>
#include <iomanip>


namespace Gadgetron
{

class DependencyQueryReader : public GadgetMessageReader
{
    public:

        DependencyQueryReader(std::string filename) : number_of_calls_(0) , filename_(filename)
        {
        }

        virtual ~DependencyQueryReader()
        {
        }

        virtual ACE_Message_Block* read(ACE_SOCK_Stream* socket)
        {
            ssize_t recv_count = 0;

            typedef unsigned long long size_t_type;

            size_t_type len(0);
            if ( ( recv_count = socket->recv_n( &len, sizeof(size_t_type)) ) <= 0 )
            {
	      GERROR("DependencyQueryReader, failed to read query results length\n");
	      return 0;
            }

            char* buf = NULL;
            try
            {
                buf = new char[len];
                if ( buf == NULL )
                {
		  GERROR("DependencyQueryReader, failed to allocate buffer\n");
		  return 0;
                }

                memset(buf, '\0', len);
                memcpy(buf, &len, sizeof(size_t_type));
            }
            catch (std::runtime_error &err)
            {
                GEXCEPTION(err,"DependencyQueryReader, failed to allocate buffer\n");
                return 0;
            }

            if ( ( recv_count = socket->recv_n( buf, len) ) <= 0 )
            {
	      GERROR("DependencyQueryReader, failed to read query results\n");
	      delete [] buf;
	      return 0;
            }

            std::ofstream outfile;
            outfile.open (filename_.c_str(), std::ios::out|std::ios::binary);

            if (outfile.good())
            {
                outfile.write(buf, len);
                outfile.close();
                number_of_calls_++;
            }
            else
            {
                delete[] buf;

                GERROR_STREAM("File " << filename_ << " is not good for writing\n");
                return 0;
            }

            delete[] buf;

            // The GadgetronConnector expects an ACE_Message_Block* (NOT NULL)
            ACE_Message_Block *mb = new ACE_Message_Block();

            return mb;
        }

    protected:

        size_t number_of_calls_;
        std::string filename_;
};

} // namespace Gadgetron

#endif
// ===== End: apps/clients/utilities/DependencyQueryReader.h =====

