find_package(ZFP)


if (ZFP_FOUND)
   add_definitions(-DGADGETRON_COMPRESSION_ZFP)
endif()

if (ZFP_FOUND)
   include_directories(${ZFP_INCLUDE_DIR})
endif()


if (NOT USE_AMALGAMATED)
    add_executable(gadgetron_ismrmrd_client gadgetron_ismrmrd_client.cpp)
    include_directories(${HDF5_INCLUDE_DIRS})
    target_link_libraries(gadgetron_ismrmrd_client ISMRMRD::ISMRMRD Boost::program_options gadgetron_mricore )

    if (ZFP_FOUND)
       target_link_libraries(gadgetron_ismrmrd_client ${ZFP_LIBRARIES})
    endif ()

    install(TARGETS gadgetron_ismrmrd_client DESTINATION bin COMPONENT main)
else()
    if (USE_SYCL)
        add_executable(gadgetron_ismrmrd_client gadgetron_ismrmrd_client_amalgamated.cpp.dp.cpp)
        target_compile_options(gadgetron_ismrmrd_client PRIVATE -fsycl -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend --cuda-gpu-arch=sm_80)
        target_link_options(gadgetron_ismrmrd_client PRIVATE -fsycl -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend --cuda-gpu-arch=sm_80)
        if (ZFP_FOUND)
            target_link_libraries(gadgetron_ismrmrd_client ${GADGETRON_AMALGAMATED_LIBS} ${ZFP_LIBRARIES} sycl OpenCL stdc++fs mkl_sycl mkl_core mkl_sycl_blas mkl_sycl_sparse)
        else()
            target_link_libraries(gadgetron_ismrmrd_client ${GADGETRON_AMALGAMATED_LIBS} sycl OpenCL stdc++fs mkl_sycl mkl_core mkl_sycl_blas mkl_sycl_sparse)
        endif()
        set_source_files_properties(gadgetron_ismrmrd_client_amalgamated.cpp.dp.cpp PROPERTIES COMPILE_FLAGS "-msse4.1")
        set_source_files_properties(gadgetron_ismrmrd_client_amalgamated.cpp.dp.cpp PROPERTIES COMPILE_FLAGS "-mavx2 -mfma")
    else()
        add_executable(gadgetron_ismrmrd_client gadgetron_ismrmrd_client_amalgamated.cpp)
        if (ZFP_FOUND)
            target_link_libraries(gadgetron_ismrmrd_client ${GADGETRON_AMALGAMATED_LIBS} ${ZFP_LIBRARIES})
        else()
            target_link_libraries(gadgetron_ismrmrd_client ${GADGETRON_AMALGAMATED_LIBS})
        endif()
        set_source_files_properties(gadgetron_ismrmrd_client_amalgamated.cpp PROPERTIES COMPILE_FLAGS "-msse4.1")
        set_source_files_properties(gadgetron_ismrmrd_client_amalgamated.cpp PROPERTIES COMPILE_FLAGS "-mavx2 -mfma")
    endif()
    install(TARGETS gadgetron_ismrmrd_client DESTINATION bin COMPONENT main)
endif()
